# Generated by Django 3.1.3 on 2021-03-27 14:28

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagementsystem',
            name='contactno',
            field=phone_field.models.PhoneField(max_length=31, unique=True),
        ),
    ]
