# Generated by Django 3.1.3 on 2021-03-27 17:36

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0002_auto_20210327_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientManagementSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('emailId', models.EmailField(max_length=254)),
                ('phno', phone_field.models.PhoneField(max_length=31, unique=True)),
                ('clientid', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macaddress', models.CharField(max_length=12)),
                ('deviceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementSystem.clientmanagementsystem')),
            ],
        ),
    ]
