# Generated by Django 3.1.3 on 2021-03-27 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0003_clientmanagementsystem_deviceinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='deviceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementSystem.clientmanagementsystem', to_field='clientid'),
        ),
    ]
